version: "3"
volumes:
  postgres-data:

services:
  server:
    container_name: "server"
    build: ./server/
    depends_on:
      - db
    ports:
      - "3001:3001"
    command: npm run dev
    volumes:
      - ${PWD}/server:/usr/src/app
      - /usr/src/app/node_modules/

  db:
    image: "postgres:12"
    container_name: "postgres"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - "5435" # Publishes 5435 to other containers but NOT to host machine original port 5432 for postgre
    ports:
      - "5435:5435"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ${PWD}/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: -p 5435
